apiVersion: v1
items:
- apiVersion: nnf.cray.hpe.com/v1alpha1
  kind: NnfDataMovement
  metadata:
    creationTimestamp: "2023-11-13T21:32:19Z"
    finalizers:
    - dm.cray.hpe.com
    generation: 1
    labels:
      dataworkflowservices.github.io/owner.kind: Workflow
      dataworkflowservices.github.io/owner.name: gfs2-with-data-movement
      dataworkflowservices.github.io/owner.namespace: default
      dataworkflowservices.github.io/workflow.name: gfs2-with-data-movement
      dataworkflowservices.github.io/workflow.namespace: default
      nnf.cray.hpe.com/directive_index: "1"
      nnf.cray.hpe.com/teardown_state: DataIn
    name: gfs2-with-data-movement-1-0
    namespace: rabbit-node-2
    resourceVersion: "139375205"
    uid: f389ce41-9db9-4ca7-9d12-c056bff9e9a2
  spec:
    cancel: false
    destination:
      path: /mnt/nnf/1f486252-bfe6-4ee7-bad6-288cead7337a-0/0
      storageReference:
        kind: NnfStorage
        name: gfs2-with-data-movement-0
        namespace: default
    groupId: 1051
    source:
      path: /lus/kelso/testuser/test.in
      storageReference:
        kind: LustreFileSystem
        name: global-kelso
        namespace: default
    userId: 1050
  status:
    commandStatus:
      command: /bin/bash -c ulimit -n 2048 && mpirun --allow-run-as-root --hostfile
        /tmp/gfs2-with-data-movement-1-0/hostfile dcp --progress 1 --uid 1050 --gid
        1051 /lus/kelso/testuser/test.in /mnt/nnf/1f486252-bfe6-4ee7-bad6-288cead7337a-0/0
      elapsedTime: 620.810421ms
      lastMessage: |
        [nnf-dm-worker-d2tmz:00037] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
      lastMessageTime: "2023-11-13T21:32:20.571763Z"
    endTime: "2023-11-13T21:32:20.580973Z"
    message: |
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Walking /lus/kelso/testuser/test.in
      [2023-11-13T21:32:20] Walked 1 items in 0.000 secs (2440.507 items/sec) ...
      [2023-11-13T21:32:20] Walked 1 items in 0.000 seconds (2009.117 items/sec)
      [2023-11-13T21:32:20] Copying to /mnt/nnf/1f486252-bfe6-4ee7-bad6-288cead7337a-0/0
      [2023-11-13T21:32:20] Items: 1
      [2023-11-13T21:32:20]   Directories: 0
      [2023-11-13T21:32:20]   Files: 1
      [2023-11-13T21:32:20]   Links: 0
      [2023-11-13T21:32:20] Data: 3.628 MiB (3.628 MiB per file)
      [2023-11-13T21:32:20] Creating 1 files.
      [2023-11-13T21:32:20] Copying data.
      [2023-11-13T21:32:20] Copy data: 3.628 MiB (3804432 bytes)
      [2023-11-13T21:32:20] Copy rate: 91.079 MiB/s (3804432 bytes in 0.040 seconds)
      [2023-11-13T21:32:20] Syncing data to disk.
      [2023-11-13T21:32:20] Sync completed in 0.024 seconds.
      [2023-11-13T21:32:20] Fixing permissions.
      [2023-11-13T21:32:20] Updated 1 items in 0.000 seconds (12547.996 items/sec)
      [2023-11-13T21:32:20] Syncing directory updates to disk.
      [2023-11-13T21:32:20] Sync completed in 0.002 seconds.
      [2023-11-13T21:32:20] Started: Nov-13-2023,21:32:20
      [2023-11-13T21:32:20] Completed: Nov-13-2023,21:32:20
      [2023-11-13T21:32:20] Seconds: 0.067
      [2023-11-13T21:32:20] Items: 1
      [2023-11-13T21:32:20]   Directories: 0
      [2023-11-13T21:32:20]   Files: 1
      [2023-11-13T21:32:20]   Links: 0
      [2023-11-13T21:32:20] Data: 3.628 MiB (3804432 bytes)
      [2023-11-13T21:32:20] Rate: 54.002 MiB/s (3804432 bytes in 0.067 seconds)
      --------------------------------------------------------------------------
      A system call failed during shared memory initialization that should
      not have.  It is likely that your MPI job will now either abort or
      experience performance degradation.

        Local host:  nnf-dm-worker-d2tmz
        System call: unlink(2) /dev/shm/vader_segment.nnf-dm-worker-d2tmz.a83e0001.2
        Error:       Operation not permitted (errno 1)
      --------------------------------------------------------------------------
      [nnf-dm-worker-d2tmz:00037] 7 more processes have sent help message help-opal-shmem-mmap.txt / sys call fail
      [nnf-dm-worker-d2tmz:00037] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
    startTime: "2023-11-13T21:32:19.943990Z"
    state: Finished
    status: Success
- apiVersion: nnf.cray.hpe.com/v1alpha1
  kind: NnfDataMovement
  metadata:
    creationTimestamp: "2023-11-13T21:32:19Z"
    finalizers:
    - dm.cray.hpe.com
    generation: 1
    labels:
      dataworkflowservices.github.io/owner.kind: Workflow
      dataworkflowservices.github.io/owner.name: gfs2-with-data-movement
      dataworkflowservices.github.io/owner.namespace: default
      dataworkflowservices.github.io/workflow.name: gfs2-with-data-movement
      dataworkflowservices.github.io/workflow.namespace: default
      nnf.cray.hpe.com/directive_index: "1"
      nnf.cray.hpe.com/teardown_state: DataIn
    name: gfs2-with-data-movement-1-0
    namespace: rabbit-node-1
    resourceVersion: "139375206"
    uid: daad554b-0c8f-4dda-b8ec-f44c403b8f61
  spec:
    cancel: false
    destination:
      path: /mnt/nnf/1f486252-bfe6-4ee7-bad6-288cead7337a-0/0
      storageReference:
        kind: NnfStorage
        name: gfs2-with-data-movement-0
        namespace: default
    groupId: 1051
    source:
      path: /lus/kelso/testuser/test.in
      storageReference:
        kind: LustreFileSystem
        name: global-kelso
        namespace: default
    userId: 1050
  status:
    commandStatus:
      command: /bin/bash -c ulimit -n 2048 && mpirun --allow-run-as-root --hostfile
        /tmp/gfs2-with-data-movement-1-0/hostfile dcp --progress 1 --uid 1050 --gid
        1051 /lus/kelso/testuser/test.in /mnt/nnf/1f486252-bfe6-4ee7-bad6-288cead7337a-0/0
      elapsedTime: 616.503633ms
      lastMessage: |
        [nnf-dm-worker-vqxn5:00038] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
      lastMessageTime: "2023-11-13T21:32:20.561007Z"
    endTime: "2023-11-13T21:32:20.567143Z"
    message: |
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Walking /lus/kelso/testuser/test.in
      [2023-11-13T21:32:20] Walked 1 items in 0.000 secs (2161.629 items/sec) ...
      [2023-11-13T21:32:20] Walked 1 items in 0.001 seconds (1814.207 items/sec)
      [2023-11-13T21:32:20] Copying to /mnt/nnf/1f486252-bfe6-4ee7-bad6-288cead7337a-0/0
      [2023-11-13T21:32:20] Items: 1
      [2023-11-13T21:32:20]   Directories: 0
      [2023-11-13T21:32:20]   Files: 1
      [2023-11-13T21:32:20]   Links: 0
      [2023-11-13T21:32:20] Data: 3.628 MiB (3.628 MiB per file)
      [2023-11-13T21:32:20] Creating 1 files.
      [2023-11-13T21:32:20] Copying data.
      [2023-11-13T21:32:20] Copy data: 3.628 MiB (3804432 bytes)
      [2023-11-13T21:32:20] Copy rate: 464.429 MiB/s (3804432 bytes in 0.008 seconds)
      [2023-11-13T21:32:20] Syncing data to disk.
      [2023-11-13T21:32:20] Sync completed in 0.055 seconds.
      [2023-11-13T21:32:20] Fixing permissions.
      [2023-11-13T21:32:20] Updated 1 items in 0.000 seconds (13858.285 items/sec)
      [2023-11-13T21:32:20] Syncing directory updates to disk.
      [2023-11-13T21:32:20] Sync completed in 0.002 seconds.
      [2023-11-13T21:32:20] Started: Nov-13-2023,21:32:20
      [2023-11-13T21:32:20] Completed: Nov-13-2023,21:32:20
      [2023-11-13T21:32:20] Seconds: 0.066
      [2023-11-13T21:32:20] Items: 1
      [2023-11-13T21:32:20]   Directories: 0
      [2023-11-13T21:32:20]   Files: 1
      [2023-11-13T21:32:20]   Links: 0
      [2023-11-13T21:32:20] Data: 3.628 MiB (3804432 bytes)
      [2023-11-13T21:32:20] Rate: 55.034 MiB/s (3804432 bytes in 0.066 seconds)
      --------------------------------------------------------------------------
      A system call failed during shared memory initialization that should
      not have.  It is likely that your MPI job will now either abort or
      experience performance degradation.

        Local host:  nnf-dm-worker-vqxn5
        System call: unlink(2) /dev/shm/vader_segment.nnf-dm-worker-vqxn5.a55f0001.5
        Error:       Operation not permitted (errno 1)
      --------------------------------------------------------------------------
      [nnf-dm-worker-vqxn5:00038] 7 more processes have sent help message help-opal-shmem-mmap.txt / sys call fail
      [nnf-dm-worker-vqxn5:00038] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
    startTime: "2023-11-13T21:32:19.938919Z"
    state: Finished
    status: Success
- apiVersion: nnf.cray.hpe.com/v1alpha1
  kind: NnfDataMovement
  metadata:
    creationTimestamp: "2023-11-13T21:32:19Z"
    finalizers:
    - dm.cray.hpe.com
    generation: 1
    labels:
      dataworkflowservices.github.io/owner.kind: Workflow
      dataworkflowservices.github.io/owner.name: gfs2-with-data-movement
      dataworkflowservices.github.io/owner.namespace: default
      dataworkflowservices.github.io/workflow.name: gfs2-with-data-movement
      dataworkflowservices.github.io/workflow.namespace: default
      nnf.cray.hpe.com/directive_index: "1"
      nnf.cray.hpe.com/teardown_state: DataIn
    name: gfs2-with-data-movement-1-1
    namespace: rabbit-node-1
    resourceVersion: "139375207"
    uid: a733cb5e-11e3-4eac-985d-14ddec169172
  spec:
    cancel: false
    destination:
      path: /mnt/nnf/1f486252-bfe6-4ee7-bad6-288cead7337a-0/1
      storageReference:
        kind: NnfStorage
        name: gfs2-with-data-movement-0
        namespace: default
    groupId: 1051
    source:
      path: /lus/kelso/testuser/test.in
      storageReference:
        kind: LustreFileSystem
        name: global-kelso
        namespace: default
    userId: 1050
  status:
    commandStatus:
      command: /bin/bash -c ulimit -n 2048 && mpirun --allow-run-as-root --hostfile
        /tmp/gfs2-with-data-movement-1-1/hostfile dcp --progress 1 --uid 1050 --gid
        1051 /lus/kelso/testuser/test.in /mnt/nnf/1f486252-bfe6-4ee7-bad6-288cead7337a-0/1
      elapsedTime: 616.266525ms
      lastMessage: |
        [nnf-dm-worker-vqxn5:00039] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
      lastMessageTime: "2023-11-13T21:32:20.561306Z"
    endTime: "2023-11-13T21:32:20.568066Z"
    message: |
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Walking /lus/kelso/testuser/test.in
      [2023-11-13T21:32:20] Walked 1 items in 0.000 secs (2215.904 items/sec) ...
      [2023-11-13T21:32:20] Walked 1 items in 0.001 seconds (1847.520 items/sec)
      [2023-11-13T21:32:20] Copying to /mnt/nnf/1f486252-bfe6-4ee7-bad6-288cead7337a-0/1
      [2023-11-13T21:32:20] Items: 1
      [2023-11-13T21:32:20]   Directories: 0
      [2023-11-13T21:32:20]   Files: 1
      [2023-11-13T21:32:20]   Links: 0
      [2023-11-13T21:32:20] Data: 3.628 MiB (3.628 MiB per file)
      [2023-11-13T21:32:20] Creating 1 files.
      [2023-11-13T21:32:20] Copying data.
      [2023-11-13T21:32:20] Copy data: 3.628 MiB (3804432 bytes)
      [2023-11-13T21:32:20] Copy rate: 475.059 MiB/s (3804432 bytes in 0.008 seconds)
      [2023-11-13T21:32:20] Syncing data to disk.
      [2023-11-13T21:32:20] Sync completed in 0.056 seconds.
      [2023-11-13T21:32:20] Fixing permissions.
      [2023-11-13T21:32:20] Updated 1 items in 0.000 seconds (13955.176 items/sec)
      [2023-11-13T21:32:20] Syncing directory updates to disk.
      [2023-11-13T21:32:20] Sync completed in 0.002 seconds.
      [2023-11-13T21:32:20] Started: Nov-13-2023,21:32:20
      [2023-11-13T21:32:20] Completed: Nov-13-2023,21:32:20
      [2023-11-13T21:32:20] Seconds: 0.066
      [2023-11-13T21:32:20] Items: 1
      [2023-11-13T21:32:20]   Directories: 0
      [2023-11-13T21:32:20]   Files: 1
      [2023-11-13T21:32:20]   Links: 0
      [2023-11-13T21:32:20] Data: 3.628 MiB (3804432 bytes)
      [2023-11-13T21:32:20] Rate: 55.037 MiB/s (3804432 bytes in 0.066 seconds)
      --------------------------------------------------------------------------
      A system call failed during shared memory initialization that should
      not have.  It is likely that your MPI job will now either abort or
      experience performance degradation.

        Local host:  nnf-dm-worker-vqxn5
        System call: unlink(2) /dev/shm/vader_segment.nnf-dm-worker-vqxn5.a55e0001.4
        Error:       Operation not permitted (errno 1)
      --------------------------------------------------------------------------
      [nnf-dm-worker-vqxn5:00039] 7 more processes have sent help message help-opal-shmem-mmap.txt / sys call fail
      [nnf-dm-worker-vqxn5:00039] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
    startTime: "2023-11-13T21:32:19.939056Z"
    state: Finished
    status: Success
- apiVersion: nnf.cray.hpe.com/v1alpha1
  kind: NnfDataMovement
  metadata:
    creationTimestamp: "2023-11-13T21:32:19Z"
    finalizers:
    - dm.cray.hpe.com
    generation: 1
    labels:
      dataworkflowservices.github.io/owner.kind: Workflow
      dataworkflowservices.github.io/owner.name: gfs2-with-data-movement
      dataworkflowservices.github.io/owner.namespace: default
      dataworkflowservices.github.io/workflow.name: gfs2-with-data-movement
      dataworkflowservices.github.io/workflow.namespace: default
      nnf.cray.hpe.com/directive_index: "1"
      nnf.cray.hpe.com/teardown_state: DataIn
    name: gfs2-with-data-movement-1-1
    namespace: rabbit-node-2
    resourceVersion: "139375208"
    uid: e146e07e-6103-4b93-99de-8cdfcab5f324
  spec:
    cancel: false
    destination:
      path: /mnt/nnf/1f486252-bfe6-4ee7-bad6-288cead7337a-0/1
      storageReference:
        kind: NnfStorage
        name: gfs2-with-data-movement-0
        namespace: default
    groupId: 1051
    source:
      path: /lus/kelso/testuser/test.in
      storageReference:
        kind: LustreFileSystem
        name: global-kelso
        namespace: default
    userId: 1050
  status:
    commandStatus:
      command: /bin/bash -c ulimit -n 2048 && mpirun --allow-run-as-root --hostfile
        /tmp/gfs2-with-data-movement-1-1/hostfile dcp --progress 1 --uid 1050 --gid
        1051 /lus/kelso/testuser/test.in /mnt/nnf/1f486252-bfe6-4ee7-bad6-288cead7337a-0/1
      elapsedTime: 618.837944ms
      lastMessage: |
        [nnf-dm-worker-d2tmz:00038] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
      lastMessageTime: "2023-11-13T21:32:20.571031Z"
    endTime: "2023-11-13T21:32:20.579472Z"
    message: |
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Set Group ID to 1051
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Set User ID to 1050
      [2023-11-13T21:32:20] Walking /lus/kelso/testuser/test.in
      [2023-11-13T21:32:20] Walked 1 items in 0.000 secs (2018.587 items/sec) ...
      [2023-11-13T21:32:20] Walked 1 items in 0.001 seconds (1694.344 items/sec)
      [2023-11-13T21:32:20] Copying to /mnt/nnf/1f486252-bfe6-4ee7-bad6-288cead7337a-0/1
      [2023-11-13T21:32:20] Items: 1
      [2023-11-13T21:32:20]   Directories: 0
      [2023-11-13T21:32:20]   Files: 1
      [2023-11-13T21:32:20]   Links: 0
      [2023-11-13T21:32:20] Data: 3.628 MiB (3.628 MiB per file)
      [2023-11-13T21:32:20] Creating 1 files.
      [2023-11-13T21:32:20] Copying data.
      [2023-11-13T21:32:20] Copy data: 3.628 MiB (3804432 bytes)
      [2023-11-13T21:32:20] Copy rate: 126.334 MiB/s (3804432 bytes in 0.029 seconds)
      [2023-11-13T21:32:20] Syncing data to disk.
      [2023-11-13T21:32:20] Sync completed in 0.024 seconds.
      [2023-11-13T21:32:20] Fixing permissions.
      [2023-11-13T21:32:20] Updated 1 items in 0.000 seconds (11057.666 items/sec)
      [2023-11-13T21:32:20] Syncing directory updates to disk.
      [2023-11-13T21:32:20] Sync completed in 0.002 seconds.
      [2023-11-13T21:32:20] Started: Nov-13-2023,21:32:20
      [2023-11-13T21:32:20] Completed: Nov-13-2023,21:32:20
      [2023-11-13T21:32:20] Seconds: 0.055
      [2023-11-13T21:32:20] Items: 1
      [2023-11-13T21:32:20]   Directories: 0
      [2023-11-13T21:32:20]   Files: 1
      [2023-11-13T21:32:20]   Links: 0
      [2023-11-13T21:32:20] Data: 3.628 MiB (3804432 bytes)
      [2023-11-13T21:32:20] Rate: 65.451 MiB/s (3804432 bytes in 0.055 seconds)
      --------------------------------------------------------------------------
      A system call failed during shared memory initialization that should
      not have.  It is likely that your MPI job will now either abort or
      experience performance degradation.

        Local host:  nnf-dm-worker-d2tmz
        System call: unlink(2) /dev/shm/vader_segment.nnf-dm-worker-d2tmz.a83d0001.4
        Error:       Operation not permitted (errno 1)
      --------------------------------------------------------------------------
      [nnf-dm-worker-d2tmz:00038] 7 more processes have sent help message help-opal-shmem-mmap.txt / sys call fail
      [nnf-dm-worker-d2tmz:00038] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
    startTime: "2023-11-13T21:32:19.944140Z"
    state: Finished
    status: Success
kind: List
metadata:
  resourceVersion: ""
