apiVersion: v1
items:
- apiVersion: nnf.cray.hpe.com/v1alpha1
  kind: NnfDataMovement
  metadata:
    creationTimestamp: "2023-11-13T20:39:22Z"
    finalizers:
    - dm.cray.hpe.com
    generateName: nnf-dm-node-
    generation: 1
    labels:
      dataworkflowservices.github.io/owner.kind: NnfDataMovement
      dataworkflowservices.github.io/owner.name: blake-gfs2
      dataworkflowservices.github.io/owner.namespace: default
      dm.cray.hpe.com/initiator: compute-node-5
      nnf.cray.hpe.com/teardown_state: PostRun
    name: nnf-dm-node-zclrc
    namespace: rabbit-node-2
    resourceVersion: "139364655"
    uid: a014ad91-de38-4d94-8ab5-5749b1db3cba
  spec:
    cancel: false
    destination:
      path: /lus/global/
      storageReference: {}
    source:
      path: /mnt/nnf/78bcd1bd-334f-4ca3-86eb-700cba268102-0/1/test.blake
      storageReference: {}
    userConfig:
      dryrun: false
      logStdout: false
      storeStdout: false
  status:
    commandStatus:
      command: /bin/bash -c ulimit -n 2048 && mpirun --allow-run-as-root --hostfile
        /tmp/nnf-dm-node-zclrc/hostfile dcp --progress 1 --uid 0 --gid 0 /mnt/nnf/78bcd1bd-334f-4ca3-86eb-700cba268102-0/1/test.blake
        /lus/global/
      elapsedTime: 4.528636435s
      lastMessage: |
        --------------------------------------------------------------------------
      lastMessageTime: "2023-11-13T20:39:26.739000Z"
      progress: 100
    endTime: "2023-11-13T20:39:26.746616Z"
    error:
      debugMessage: exit status 1
      severity: Fatal
      type: Internal
      userMessage: |
        data movement operation failed: [2023-11-13T20:39:22] Walking /mnt/nnf/78bcd1bd-334f-4ca3-86eb-700cba268102-0/1/test.blake
        [2023-11-13T20:39:22] Walked 1 items in 0.001 secs (1917.924 items/sec) ...
        [2023-11-13T20:39:22] Walked 1 items in 0.001 seconds (1621.584 items/sec)
        [2023-11-13T20:39:22] Copying to /lus/global
        [2023-11-13T20:39:22] Items: 1
        [2023-11-13T20:39:22]   Directories: 0
        [2023-11-13T20:39:22]   Files: 1
        [2023-11-13T20:39:22]   Links: 0
        [2023-11-13T20:39:22] Data: 2.794 GiB (2.794 GiB per file)
        [2023-11-13T20:39:22] Creating 1 files.
        [2023-11-13T20:39:22] [0] [/deps/mpifileutils/src/common/mfu_flist_copy.c:422] ERROR: Failed to set value for name=security.selinux on `/lus/global/test.blake' lsetxattr() (errno=95 Operation not supported)
        [2023-11-13T20:39:22] Copying data.
        [2023-11-13T20:39:23] Copied 1.953 GiB (70%) in 1.057 secs (1.848 GiB/s) 0 secs left ...
        [2023-11-13T20:39:24] Copied 2.794 GiB (100%) in 2.036 secs (1.372 GiB/s) done
        [2023-11-13T20:39:24] Copy data: 2.794 GiB (3000000000 bytes)
        [2023-11-13T20:39:24] Copy rate: 1.372 GiB/s (3000000000 bytes in 2.037 seconds)
        [2023-11-13T20:39:24] Syncing data to disk.
        [2023-11-13T20:39:24] Sync completed in 0.022 seconds.
        [2023-11-13T20:39:24] Fixing permissions.
        [2023-11-13T20:39:24] Updated 1 items in 0.000 seconds (2181.429 items/sec)
        [2023-11-13T20:39:24] Syncing directory updates to disk.
        [2023-11-13T20:39:24] Sync completed in 0.001 seconds.
        [2023-11-13T20:39:24] Started: Nov-13-2023,20:39:22
        [2023-11-13T20:39:24] Completed: Nov-13-2023,20:39:24
        [2023-11-13T20:39:24] Seconds: 2.061
        [2023-11-13T20:39:24] Items: 1
        [2023-11-13T20:39:24]   Directories: 0
        [2023-11-13T20:39:24]   Files: 1
        [2023-11-13T20:39:24]   Links: 0
        [2023-11-13T20:39:24] Data: 2.794 GiB (3000000000 bytes)
        [2023-11-13T20:39:24] Rate: 1.355 GiB/s (3000000000 bytes in 2.061 seconds)
        [2023-11-13T20:39:24] [0] [/deps/mpifileutils/src/dcp/dcp.c:574] ERROR: One or more errors were detected while copying: MFU_ERR(-1101)
        --------------------------------------------------------------------------
        Primary job  terminated normally, but 1 process returned
        a non-zero exit code. Per user-direction, the job has been aborted.
        --------------------------------------------------------------------------
        --------------------------------------------------------------------------
        mpirun detected that one or more processes exited with non-zero status, thus causing
        the job to be terminated. The first process to do so was:

          Process name: [[15337,1],3]
          Exit code:    1
        --------------------------------------------------------------------------
    message: |
      exit status 1: [2023-11-13T20:39:22] Walking /mnt/nnf/78bcd1bd-334f-4ca3-86eb-700cba268102-0/1/test.blake
      [2023-11-13T20:39:22] Walked 1 items in 0.001 secs (1917.924 items/sec) ...
      [2023-11-13T20:39:22] Walked 1 items in 0.001 seconds (1621.584 items/sec)
      [2023-11-13T20:39:22] Copying to /lus/global
      [2023-11-13T20:39:22] Items: 1
      [2023-11-13T20:39:22]   Directories: 0
      [2023-11-13T20:39:22]   Files: 1
      [2023-11-13T20:39:22]   Links: 0
      [2023-11-13T20:39:22] Data: 2.794 GiB (2.794 GiB per file)
      [2023-11-13T20:39:22] Creating 1 files.
      [2023-11-13T20:39:22] [0] [/deps/mpifileutils/src/common/mfu_flist_copy.c:422] ERROR: Failed to set value for name=security.selinux on `/lus/global/test.blake' lsetxattr() (errno=95 Operation not supported)
      [2023-11-13T20:39:22] Copying data.
      [2023-11-13T20:39:23] Copied 1.953 GiB (70%) in 1.057 secs (1.848 GiB/s) 0 secs left ...
      [2023-11-13T20:39:24] Copied 2.794 GiB (100%) in 2.036 secs (1.372 GiB/s) done
      [2023-11-13T20:39:24] Copy data: 2.794 GiB (3000000000 bytes)
      [2023-11-13T20:39:24] Copy rate: 1.372 GiB/s (3000000000 bytes in 2.037 seconds)
      [2023-11-13T20:39:24] Syncing data to disk.
      [2023-11-13T20:39:24] Sync completed in 0.022 seconds.
      [2023-11-13T20:39:24] Fixing permissions.
      [2023-11-13T20:39:24] Updated 1 items in 0.000 seconds (2181.429 items/sec)
      [2023-11-13T20:39:24] Syncing directory updates to disk.
      [2023-11-13T20:39:24] Sync completed in 0.001 seconds.
      [2023-11-13T20:39:24] Started: Nov-13-2023,20:39:22
      [2023-11-13T20:39:24] Completed: Nov-13-2023,20:39:24
      [2023-11-13T20:39:24] Seconds: 2.061
      [2023-11-13T20:39:24] Items: 1
      [2023-11-13T20:39:24]   Directories: 0
      [2023-11-13T20:39:24]   Files: 1
      [2023-11-13T20:39:24]   Links: 0
      [2023-11-13T20:39:24] Data: 2.794 GiB (3000000000 bytes)
      [2023-11-13T20:39:24] Rate: 1.355 GiB/s (3000000000 bytes in 2.061 seconds)
      [2023-11-13T20:39:24] [0] [/deps/mpifileutils/src/dcp/dcp.c:574] ERROR: One or more errors were detected while copying: MFU_ERR(-1101)
      --------------------------------------------------------------------------
      Primary job  terminated normally, but 1 process returned
      a non-zero exit code. Per user-direction, the job has been aborted.
      --------------------------------------------------------------------------
      --------------------------------------------------------------------------
      mpirun detected that one or more processes exited with non-zero status, thus causing
      the job to be terminated. The first process to do so was:

        Process name: [[15337,1],3]
        Exit code:    1
      --------------------------------------------------------------------------
    startTime: "2023-11-13T20:39:22.203310Z"
    state: Finished
    status: Failed
kind: List
metadata:
  resourceVersion: ""
