apiVersion: dataworkflowservices.github.io/v1alpha2
kind: Workflow
metadata:
  name: webserver2
  namespace: default
spec:
  desiredState: 'Proposal'
  dwDirectives:
    #- "#DW jobdw name=blake-gfs2 type=gfs2 capacity=50GB"
    # - "#DW persistentdw name=blake-persistent"
    - '#DW container name=webserver2 profile=example-mpi-webserver'
      # DW_PERSISTENT_foo-persistent-storage=blake-persistent"
  wlmID: '5f239bd8-30db-450b-8c2c-a1a7c8631a1a'
  jobID: 900001
  # userID: 1050
  # groupID: 1200
  userID: 1050
  groupID: 1051
