apiVersion: dataworkflowservices.github.io/v1alpha2
kind: Workflow
metadata:
  name: blake-container-mpi
  namespace: default
spec:
  desiredState: 'Proposal'
  dwDirectives:
    - '#DW jobdw name=blake-gfs2-mpi type=gfs2 capacity=50GB'
    # - "#DW persistentdw name=blake-persistent"
    - "#DW container name=blake-container-mpi profile=example-mpi-webserver \
      DW_JOB_foo_local_storage=blake-gfs2-mpi"
      # DW_PERSISTENT_foo-persistent-storage=blake-persistent"
  wlmID: '5f239bd8-30db-450b-8c2c-a1a7c8631a1a'
  jobID: 900002
  userID: 1500
  groupID: 1600
