apiVersion: dataworkflowservices.github.io/v1alpha2
kind: Workflow
metadata:
  name: blake-gfs2-copy-in-out
  namespace: default
spec:
  desiredState: 'Proposal'
  dwDirectives:
    - '#DW jobdw type=gfs2 capacity=50GB name=blake-gfs2-copy-in-out'
    - '#DW copy_in source=/lus/global/mpiuser/perl destination=$DW_JOB_blake-gfs2-copy-in-out/'
    - '#DW copy_out source=$DW_JOB_blake-gfs2-copy-in-out/perl destination=/lus/global/mpiuser/perl2'
  wlmID: '5f239bd8-30db-450b-8c2c-a1a7c8631a1a'
  jobID: 900003
  userID: 1050
  groupID: 1051
