apiVersion: dataworkflowservices.github.io/v1alpha2
kind: Workflow
metadata:
  name: blake-gfs2-2
  namespace: default
spec:
  desiredState: 'Proposal'
  dwDirectives:
    - '#DW jobdw type=gfs2 capacity=1GB name=blake-gfs2-2'
  wlmID: '5f239bd8-30db-450b-8c2c-a1a7c8631a1a'
  jobID: 900002
  userID: 1041
  groupID: 999
