apiVersion: lus.cray.hpe.com/v1beta1
kind: LustreFileSystem
metadata:
  name: lushtx
  namespace: default
spec:
  name: lushtx
  mountRoot: /lus/global
  namespaces:
    default:
      modes:
        - ReadWriteMany
  mgsNids: 10.1.1.113@tcp
