apiVersion: v1
items:
- apiVersion: nnf.cray.hpe.com/v1alpha1
  kind: NnfStorage
  metadata:
    creationTimestamp: "2024-03-11T17:02:15Z"
    finalizers:
    - nnf.cray.hpe.com/nnf_storage
    - fluxjob-36172110648836096-0-servers
    generation: 1
    labels:
      dataworkflowservices.github.io/owner.kind: Workflow
      dataworkflowservices.github.io/owner.name: fluxjob-36172110648836096
      dataworkflowservices.github.io/owner.namespace: default
      dataworkflowservices.github.io/owner.uid: 49ad1cd2-2827-4b73-a872-7b8205e34b76
      dataworkflowservices.github.io/workflow.name: fluxjob-36172110648836096
      dataworkflowservices.github.io/workflow.namespace: default
      dataworkflowservices.github.io/workflow.uid: 49ad1cd2-2827-4b73-a872-7b8205e34b76
      nnf.cray.hpe.com/directive_index: "0"
      nnf.cray.hpe.com/pinned_storage_profile_name: fluxjob-36172110648836096-0
      nnf.cray.hpe.com/pinned_storage_profile_namespace: default
    name: fluxjob-36172110648836096-0
    namespace: default
    ownerReferences:
    - apiVersion: dataworkflowservices.github.io/v1alpha2
      blockOwnerDeletion: true
      controller: true
      kind: Workflow
      name: fluxjob-36172110648836096
      uid: 49ad1cd2-2827-4b73-a872-7b8205e34b76
    resourceVersion: "170633262"
    uid: 951762f7-1520-450e-a6f0-44df93892ccc
  spec:
    allocationSets:
    - capacity: 10737418240
      name: gfs2
      nodes:
      - count: 2
        name: rabbit-node-1
      - count: 2
        name: rabbit-node-2
      persistentMgsReference: {}
    fileSystemType: gfs2
    groupID: 100
    userID: 1060
  status:
    allocationSets:
    - allocationCount: 4
      ready: true
    ready: true
kind: List
metadata:
  resourceVersion: ""
