apiVersion: dataworkflowservices.github.io/v1alpha2
kind: Workflow
metadata:
  name: blake-persistent
  namespace: default
spec:
  desiredState: 'Proposal'
  dwDirectives:
    - '#DW create_persistent type=lustre capacity=50GB name=blake-persistent'
  wlmID: '5f239bd8-30db-450b-8c2c-a1a7c8631a1a'
  jobID: 900001
  userID: 1050
  groupID: 1051
