# Flux needs to know the path to the IMP executable
[exec]
imp = "/usr/libexec/flux/flux-imp"

# Allow users other than the instance owner (guests) to connect to Flux
# Optionally, root may be given "owner privileges" for convenience
[access]
allow-guest-user = true
allow-root-owner = true

# Point to shared network certificate generated flux-keygen(1).
# Define the network endpoints for Flux's tree based overlay network
# and inform Flux of the hostnames that will start flux-broker(1).
[bootstrap]
curve_cert = "/etc/flux/system/curve.cert"

#default_port = 8050
#default_bind = "tcp://eth0:%p"
#default_connect = "tcp://%h:%p"

# Rank 0 is the TBON parent of all brokers unless explicitly set with
# parent directives.
hosts = [
    { host="htx-lustre", bind="tcp://ens10f3:9001", connect="tcp://10.1.1.113:9001" },
    { host="rabbit-compute-[2-5]" },
]

# Speed up detection of crashed network peers (system default is around 20m)
[tbon]
tcp_user_timeout = "2m"

# Uncomment 'norestrict' if flux broker is constrained to system cores by
# systemd or other site policy.  This allows jobs to run on assigned cores.
# Uncomment 'exclude' to avoid scheduling jobs on certain nodes (e.g. login,
# management, or service nodes).
[resource]
norestrict = true
exclude = "htx-lustre"

[[resource.config]]
hosts = "rabbit-compute-[2,4]"
properties = ["one"]
cores = "0-63"

[[resource.config]]
hosts = "rabbit-compute-[3,5]"
properties = ["two"]
cores = "0-63"

[[resource.config]]
hosts = "htx-lustre"
properties = ["exclude"]
cores = "0-63"

[queues.one]
requires = ["one"]

[queues.two]
requires = ["two"]

[queues.exclude]
requires = ["exclude"]

# Store the kvs root hash in sqlite periodically in case of broker crash.
# Recommend offline KVS garbage collection when commit threshold is reached.
[kvs]
checkpoint-period = "30m"
gc-threshold = 100000

# Immediately reject jobs with invalid jobspec or unsatisfiable resources
[ingest.validator]
plugins = [ "jobspec", "feasibility" ]

# Remove inactive jobs from the KVS after one week.
[job-manager]
inactive-age-limit = "7d"
plugins = [
  { load = "dws-jobtap.so" }
]

# Jobs submitted without duration get a very short one
[policy.jobspec.defaults.system]
duration = "1m"
queue = "one"

# Jobs that explicitly request more than the following limits are rejected
[policy.limits]
duration = "2h"
job-size.max.nnodes = 8
job-size.max.ncores = 32

# Configure the flux-sched (fluxion) scheduler policies
# The 'lonodex' match policy selects node-exclusive scheduling, and can be
# commented out if jobs may share nodes.
[sched-fluxion-qmanager]
queue-policy = "easy"
[sched-fluxion-resource]
match-policy = "lonodex"
match-format = "rv1_nosched"